export const players = [
  {
    "uniform_number": "12",
    "real_name": "矢澤 宏太",
    "furigana": "やざわ　こうた",
    "birthday": "2000年08月02日",
    "age": "22歳",
    "height": "173cm",
    "weight": "71kg",
    "birthplace": "東京都",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "13",
    "real_name": "生田目 翼",
    "furigana": "なばため　つばさ",
    "birthday": "1995年02月19日",
    "age": "28歳",
    "height": "176cm",
    "weight": "88kg",
    "birthplace": "茨城県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "14",
    "real_name": "加藤 貴之",
    "furigana": "かとう　たかゆき",
    "birthday": "1992年06月03日",
    "age": "31歳",
    "height": "182cm",
    "weight": "90kg",
    "birthplace": "千葉県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "15",
    "real_name": "上沢 直之",
    "furigana": "うわさわ　なおゆき",
    "birthday": "1994年02月06日",
    "age": "29歳",
    "height": "187cm",
    "weight": "88kg",
    "birthplace": "千葉県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "16",
    "real_name": "達 孝太",
    "furigana": "たつ　こうた",
    "birthday": "2004年03月27日",
    "age": "19歳",
    "height": "194cm",
    "weight": "94kg",
    "birthplace": "大阪府",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "17",
    "real_name": "伊藤 大海",
    "furigana": "いとう　ひろみ",
    "birthday": "1997年08月31日",
    "age": "25歳",
    "height": "176cm",
    "weight": "82kg",
    "birthplace": "北海道",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "18",
    "real_name": "吉田 輝星",
    "furigana": "よしだ　こうせい",
    "birthday": "2001年01月12日",
    "age": "22歳",
    "height": "175cm",
    "weight": "83kg",
    "birthplace": "秋田県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "19",
    "real_name": "玉井 大翔",
    "furigana": "たまい　たいしょう",
    "birthday": "1992年06月16日",
    "age": "30歳",
    "height": "178cm",
    "weight": "78kg",
    "birthplace": "北海道",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "20",
    "real_name": "上原 健太",
    "furigana": "うえはら　けんた",
    "birthday": "1994年03月29日",
    "age": "29歳",
    "height": "191cm",
    "weight": "90kg",
    "birthplace": "沖縄県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "22",
    "real_name": "杉浦 稔大",
    "furigana": "すぎうら　としひろ",
    "birthday": "1992年02月25日",
    "age": "31歳",
    "height": "190cm",
    "weight": "88kg",
    "birthplace": "北海道",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "24",
    "real_name": "金村 尚真",
    "furigana": "かねむら　しょうま",
    "birthday": "2000年08月29日",
    "age": "22歳",
    "height": "176cm",
    "weight": "83kg",
    "birthplace": "沖縄県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "25",
    "real_name": "宮西 尚生",
    "furigana": "みやにし　なおき",
    "birthday": "1985年06月02日",
    "age": "38歳",
    "height": "180cm",
    "weight": "78kg",
    "birthplace": "兵庫県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "26",
    "real_name": "田中 正義",
    "furigana": "たなか せいぎ",
    "birthday": "1994年07月19日",
    "age": "28歳",
    "height": "188cm",
    "weight": "93kg",
    "birthplace": "神奈川県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "28",
    "real_name": "河野 竜生",
    "furigana": "かわの　りゅうせい",
    "birthday": "1998年05月30日",
    "age": "25歳",
    "height": "175cm",
    "weight": "80kg",
    "birthplace": "徳島県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "29",
    "real_name": "井口 和朋",
    "furigana": "いぐち　かずとも",
    "birthday": "1994年01月07日",
    "age": "29歳",
    "height": "175cm",
    "weight": "75kg",
    "birthplace": "神奈川県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "33",
    "real_name": "立野 和明",
    "furigana": "たての　かずあき",
    "birthday": "1998年04月03日",
    "age": "25歳",
    "height": "181cm",
    "weight": "87kg",
    "birthplace": "愛知県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "34",
    "real_name": "堀 瑞輝",
    "furigana": "ほり　みずき",
    "birthday": "1998年05月10日",
    "age": "25歳",
    "height": "177cm",
    "weight": "82kg",
    "birthplace": "広島県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "40",
    "real_name": "福田 俊",
    "furigana": "ふくだ　すぐる",
    "birthday": "1996年12月14日",
    "age": "26歳",
    "height": "171cm",
    "weight": "71kg",
    "birthplace": "北海道",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "41",
    "real_name": "ブライアン・ロドリゲス",
    "furigana": "ぶらいあん・ろどりげす",
    "birthday": "1991年07月06日",
    "age": "31歳",
    "height": "196cm",
    "weight": "116kg",
    "birthplace": "ドミニカ共和国",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "42",
    "real_name": "ジョン・ガント",
    "furigana": "じょん・がんと",
    "birthday": "1992年08月06日",
    "age": "30歳",
    "height": "193cm",
    "weight": "92kg",
    "birthplace": "アメリカ合衆国",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "45",
    "real_name": "コディ・ポンセ",
    "furigana": "こでぃ・ぽんせ",
    "birthday": "1994年04月25日",
    "age": "29歳",
    "height": "198cm",
    "weight": "116kg",
    "birthplace": "アメリカ合衆国",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "46",
    "real_name": "畔柳 亨丞",
    "furigana": "くろやなぎ　きょうすけ",
    "birthday": "2003年05月03日",
    "age": "20歳",
    "height": "180cm",
    "weight": "85kg",
    "birthplace": "愛知県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "47",
    "real_name": "鈴木 健矢",
    "furigana": "すずき　けんや",
    "birthday": "1997年12月11日",
    "age": "25歳",
    "height": "176cm",
    "weight": "75kg",
    "birthplace": "千葉県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "48",
    "real_name": "齋藤 友貴哉",
    "furigana": "さいとう　ゆきや",
    "birthday": "1995年01月05日",
    "age": "28歳",
    "height": "184cm",
    "weight": "92kg",
    "birthplace": "山形県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "51",
    "real_name": "石川 直也",
    "furigana": "いしかわ　なおや",
    "birthday": "1996年07月11日",
    "age": "26歳",
    "height": "192cm",
    "weight": "96kg",
    "birthplace": "山形県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "52",
    "real_name": "池田 隆英",
    "furigana": "いけだ　たかひで",
    "birthday": "1994年10月01日",
    "age": "28歳",
    "height": "181cm",
    "weight": "91kg",
    "birthplace": "佐賀県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "53",
    "real_name": "長谷川 威展",
    "furigana": "はせがわ　たけひろ",
    "birthday": "1999年08月09日",
    "age": "23歳",
    "height": "178cm",
    "weight": "85kg",
    "birthplace": "埼玉県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "54",
    "real_name": "安西 叶翔",
    "furigana": "あんざい　かなと",
    "birthday": "2004年11月13日",
    "age": "18歳",
    "height": "186cm",
    "weight": "86kg",
    "birthplace": "京都府",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "55",
    "real_name": "松浦 慶斗",
    "furigana": "まつうら　けいと",
    "birthday": "2003年07月01日",
    "age": "19歳",
    "height": "186cm",
    "weight": "101kg",
    "birthplace": "宮城県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "57",
    "real_name": "北山 亘基",
    "furigana": "きたやま　こうき",
    "birthday": "1999年04月10日",
    "age": "24歳",
    "height": "182cm",
    "weight": "80kg",
    "birthplace": "京都府",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "59",
    "real_name": "根本 悠楓",
    "furigana": "ねもと　はるか",
    "birthday": "2003年03月31日",
    "age": "20歳",
    "height": "173cm",
    "weight": "77kg",
    "birthplace": "北海道",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "62",
    "real_name": "宮内 春輝",
    "furigana": "みやうち　はるき",
    "birthday": "1996年05月25日",
    "age": "27歳",
    "height": "176cm",
    "weight": "75kg",
    "birthplace": "千葉県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "63",
    "real_name": "北浦 竜次",
    "furigana": "きたうら　りゅうじ",
    "birthday": "2000年01月12日",
    "age": "23歳",
    "height": "184cm",
    "weight": "99kg",
    "birthplace": "栃木県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "67",
    "real_name": "齋藤 綱記",
    "furigana": "さいとう　こうき",
    "birthday": "1996年12月18日",
    "age": "26歳",
    "height": "182cm",
    "weight": "93kg",
    "birthplace": "北海道",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "68",
    "real_name": "松岡 洸希",
    "furigana": "まつおか　こうき",
    "birthday": "2000年08月31日",
    "age": "22歳",
    "height": "180cm",
    "weight": "85kg",
    "birthplace": "埼玉県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "70",
    "real_name": "コナー・メネズ",
    "furigana": "こなー・めねず",
    "birthday": "1995年05月29日",
    "age": "28歳",
    "height": "188cm",
    "weight": "93kg",
    "birthplace": "アメリカ合衆国",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "93",
    "real_name": "田中 瑛斗",
    "furigana": "たなか　えいと",
    "birthday": "1999年07月13日",
    "age": "23歳",
    "height": "184cm",
    "weight": "80kg",
    "birthplace": "大分県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "114",
    "real_name": "松本 遼大",
    "furigana": "まつもと　りょうだい",
    "birthday": "2002年05月17日",
    "age": "21歳",
    "height": "188cm",
    "weight": "89kg",
    "birthplace": "岩手県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "115",
    "real_name": "齊藤 伸治",
    "furigana": "さいとう　しんじ",
    "birthday": "1998年06月13日",
    "age": "25歳",
    "height": "181cm",
    "weight": "82kg",
    "birthplace": "千葉県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "121",
    "real_name": "福島 蓮",
    "furigana": "ふくしま　れん",
    "birthday": "2003年04月25日",
    "age": "20歳",
    "height": "190cm",
    "weight": "70kg",
    "birthplace": "青森県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "123",
    "real_name": "柳川 大晟",
    "furigana": "やながわ　たいせい",
    "birthday": "2003年08月21日",
    "age": "19歳",
    "height": "191cm",
    "weight": "87kg",
    "birthplace": "大分県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "126",
    "real_name": "中山 晶量",
    "furigana": "なかやま　てるかず",
    "birthday": "1999年02月08日",
    "age": "24歳",
    "height": "188cm",
    "weight": "90kg",
    "birthplace": "徳島県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "128",
    "real_name": "山本 晃大",
    "furigana": "やまもと　こうだい",
    "birthday": "1999年04月23日",
    "age": "24歳",
    "height": "186cm",
    "weight": "88kg",
    "birthplace": "三重県",
    "bats_and_throws": "左投げ/左打ち"
  },
  {
    "uniform_number": "137",
    "real_name": "柿木 蓮",
    "furigana": "かきぎ　れん",
    "birthday": "2000年06月25日",
    "age": "22歳",
    "height": "181cm",
    "weight": "87kg",
    "birthplace": "佐賀県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "161",
    "real_name": "姫野 優也",
    "furigana": "ひめの　ゆうや",
    "birthday": "1997年04月02日",
    "age": "26歳",
    "height": "184cm",
    "weight": "96kg",
    "birthplace": "大阪府",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "2",
    "real_name": "アリエル・マルティネス",
    "furigana": "ありえる・まるてぃねす",
    "birthday": "1996年05月28日",
    "age": "27歳",
    "height": "190cm",
    "weight": "95kg",
    "birthplace": "キューバ共和国",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "10",
    "real_name": "清水 優心",
    "furigana": "しみず　ゆうし",
    "birthday": "1996年05月22日",
    "age": "27歳",
    "height": "185cm",
    "weight": "91kg",
    "birthplace": "山口県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "23",
    "real_name": "伏見 寅威",
    "furigana": "ふしみ　とらい",
    "birthday": "1990年05月12日",
    "age": "33歳",
    "height": "182cm",
    "weight": "87kg",
    "birthplace": "北海道",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "27",
    "real_name": "古川 裕大",
    "furigana": "ふるかわ　ゆうだい",
    "birthday": "1998年06月19日",
    "age": "24歳",
    "height": "182cm",
    "weight": "88kg",
    "birthplace": "福岡県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "30",
    "real_name": "宇佐見 真吾",
    "furigana": "うさみ　しんご",
    "birthday": "1993年06月04日",
    "age": "30歳",
    "height": "181cm",
    "weight": "88kg",
    "birthplace": "千葉県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "60",
    "real_name": "郡 拓也",
    "furigana": "こおり　たくや",
    "birthday": "1998年04月25日",
    "age": "25歳",
    "height": "179cm",
    "weight": "88kg",
    "birthplace": "東京都",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "64",
    "real_name": "田宮 裕涼",
    "furigana": "たみや　ゆあ",
    "birthday": "2000年06月13日",
    "age": "23歳",
    "height": "175cm",
    "weight": "79kg",
    "birthplace": "千葉県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "65",
    "real_name": "梅林 優貴",
    "furigana": "うめばやし　ゆうき",
    "birthday": "1998年03月14日",
    "age": "25歳",
    "height": "173cm",
    "weight": "81kg",
    "birthplace": "広島県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "3",
    "real_name": "加藤 豪将",
    "furigana": "かとう　ごうすけ",
    "birthday": "1994年10月08日",
    "age": "28歳",
    "height": "185cm",
    "weight": "91kg",
    "birthplace": "アメリカ合衆国",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "4",
    "real_name": "上川畑 大悟",
    "furigana": "かみかわばた　だいご",
    "birthday": "1997年01月12日",
    "age": "26歳",
    "height": "167cm",
    "weight": "71kg",
    "birthplace": "岡山県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "5",
    "real_name": "野村 佑希",
    "furigana": "のむら　ゆうき",
    "birthday": "2000年06月26日",
    "age": "22歳",
    "height": "187cm",
    "weight": "93kg",
    "birthplace": "アメリカ合衆国",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "6",
    "real_name": "アリスメンディ・アルカンタラ",
    "furigana": "ありすめんでぃ・あるかんたら",
    "birthday": "1991年10月29日",
    "age": "31歳",
    "height": "178cm",
    "weight": "85kg",
    "birthplace": "ドミニカ共和国",
    "bats_and_throws": "右投げ/両打ち"
  },
  {
    "uniform_number": "9",
    "real_name": "中島 卓也",
    "furigana": "なかしま　たくや",
    "birthday": "1991年01月11日",
    "age": "32歳",
    "height": "178cm",
    "weight": "73kg",
    "birthplace": "福岡県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "21",
    "real_name": "清宮 幸太郎",
    "furigana": "きよみや　こうたろう",
    "birthday": "1999年05月25日",
    "age": "24歳",
    "height": "184cm",
    "weight": "94kg",
    "birthplace": "東京都",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "32",
    "real_name": "谷内 亮太",
    "furigana": "やち　りょうた",
    "birthday": "1991年02月03日",
    "age": "32歳",
    "height": "177cm",
    "weight": "80kg",
    "birthplace": "石川県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "35",
    "real_name": "福田 光輝",
    "furigana": "ふくだ　こうき",
    "birthday": "1997年11月16日",
    "age": "25歳",
    "height": "176cm",
    "weight": "80kg",
    "birthplace": "大阪府",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "38",
    "real_name": "石井 一成",
    "furigana": "いしい　かずなり",
    "birthday": "1994年05月06日",
    "age": "29歳",
    "height": "182cm",
    "weight": "80kg",
    "birthplace": "栃木県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "39",
    "real_name": "有薗 直輝",
    "furigana": "ありぞの　なおき",
    "birthday": "2003年05月21日",
    "age": "20歳",
    "height": "185cm",
    "weight": "95kg",
    "birthplace": "千葉県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "43",
    "real_name": "水野 達稀",
    "furigana": "みずの　たつき",
    "birthday": "2000年07月30日",
    "age": "22歳",
    "height": "171cm",
    "weight": "75kg",
    "birthplace": "香川県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "44",
    "real_name": "阪口 樂",
    "furigana": "さかぐち　うた",
    "birthday": "2003年06月24日",
    "age": "19歳",
    "height": "187cm",
    "weight": "88kg",
    "birthplace": "京都府",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "49",
    "real_name": "山田 遥楓",
    "furigana": "やまだ　はるか",
    "birthday": "1996年09月30日",
    "age": "26歳",
    "height": "180cm",
    "weight": "84kg",
    "birthplace": "佐賀県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "56",
    "real_name": "細川 凌平",
    "furigana": "ほそかわ　りょうへい",
    "birthday": "2002年04月25日",
    "age": "21歳",
    "height": "174cm",
    "weight": "73kg",
    "birthplace": "京都府",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "58",
    "real_name": "奈良間 大己",
    "furigana": "ならま　たいき",
    "birthday": "2000年05月08日",
    "age": "23歳",
    "height": "172cm",
    "weight": "72kg",
    "birthplace": "静岡県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "94",
    "real_name": "アレン・ハンソン",
    "furigana": "あれん・はんそん",
    "birthday": "1992年10月22日",
    "age": "30歳",
    "height": "183cm",
    "weight": "77kg",
    "birthplace": "ドミニカ共和国",
    "bats_and_throws": "右投げ/両打ち"
  },
  {
    "uniform_number": "7",
    "real_name": "松本 剛",
    "furigana": "まつもと　ごう",
    "birthday": "1993年08月11日",
    "age": "29歳",
    "height": "180cm",
    "weight": "81kg",
    "birthplace": "埼玉県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "8",
    "real_name": "淺間 大基",
    "furigana": "あさま　だいき",
    "birthday": "1996年06月21日",
    "age": "26歳",
    "height": "183cm",
    "weight": "82kg",
    "birthplace": "東京都",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "36",
    "real_name": "木村 文紀",
    "furigana": "きむら　ふみかず",
    "birthday": "1988年09月13日",
    "age": "34歳",
    "height": "183cm",
    "weight": "86kg",
    "birthplace": "東京都",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "37",
    "real_name": "江越 大賀",
    "furigana": "えごし　たいが",
    "birthday": "1993年03月12日",
    "age": "30歳",
    "height": "182cm",
    "weight": "81kg",
    "birthplace": "長崎県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "50",
    "real_name": "五十幡 亮汰",
    "furigana": "いそばた　りょうた",
    "birthday": "1998年11月27日",
    "age": "24歳",
    "height": "171cm",
    "weight": "65kg",
    "birthplace": "埼玉県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "61",
    "real_name": "今川 優馬",
    "furigana": "いまがわ　ゆうま",
    "birthday": "1997年01月25日",
    "age": "26歳",
    "height": "177cm",
    "weight": "86kg",
    "birthplace": "北海道",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "66",
    "real_name": "万波 中正",
    "furigana": "まんなみ　ちゅうせい",
    "birthday": "2000年04月07日",
    "age": "23歳",
    "height": "192cm",
    "weight": "96kg",
    "birthplace": "東京都",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "124",
    "real_name": "阿部 和広",
    "furigana": "あべ　かずひろ",
    "birthday": "2003年05月12日",
    "age": "20歳",
    "height": "170cm",
    "weight": "62kg",
    "birthplace": "神奈川県",
    "bats_and_throws": "右投げ/両打ち"
  },
  {
    "uniform_number": "125",
    "real_name": "藤田 大清",
    "furigana": "ふじた　たいせい",
    "birthday": "2004年08月23日",
    "age": "18歳",
    "height": "187cm",
    "weight": "84kg",
    "birthplace": "長野県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "127",
    "real_name": "山口 アタル",
    "furigana": "やまぐち　あたる",
    "birthday": "1999年05月28日",
    "age": "24歳",
    "height": "179cm",
    "weight": "89kg",
    "birthplace": "カナダ",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "199",
    "real_name": "王 柏融",
    "furigana": "わん・ぼーろん",
    "birthday": "1993年09月09日",
    "age": "29歳",
    "height": "182cm",
    "weight": "91kg",
    "birthplace": "台湾",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "1",
    "real_name": "新庄 剛志",
    "furigana": "しんじょう　つよし",
    "birthday": "1972年01月28日",
    "age": "51歳",
    "height": "182cm",
    "weight": "76kg",
    "birthplace": "福岡県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "77",
    "real_name": "林 孝哉",
    "furigana": "はやし　たかや",
    "birthday": "1973年06月01日",
    "age": "50歳",
    "height": "177cm",
    "weight": "80kg",
    "birthplace": "和歌山県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "81",
    "real_name": "建山 義紀",
    "furigana": "たてやま　よしのり",
    "birthday": "1975年12月26日",
    "age": "47歳",
    "height": "178cm",
    "weight": "80kg",
    "birthplace": "大阪府",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "82",
    "real_name": "加藤 武治",
    "furigana": "かとう　たけはる",
    "birthday": "1978年03月24日",
    "age": "45歳",
    "height": "188cm",
    "weight": "83kg",
    "birthplace": "山形県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "89",
    "real_name": "八木 裕",
    "furigana": "やぎ　ひろし",
    "birthday": "1965年06月08日",
    "age": "58歳",
    "height": "182cm",
    "weight": "77kg",
    "birthplace": "岡山県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "72",
    "real_name": "山田 勝彦",
    "furigana": "やまだ　かつひこ",
    "birthday": "1969年07月02日",
    "age": "53歳",
    "height": "183cm",
    "weight": "88kg",
    "birthplace": "愛知県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "71",
    "real_name": "飯山 裕志",
    "furigana": "いいやま　ゆうじ",
    "birthday": "1979年07月13日",
    "age": "43歳",
    "height": "178cm",
    "weight": "79kg",
    "birthplace": "鹿児島県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "80",
    "real_name": "森本 稀哲",
    "furigana": "もりもと　ひちょり",
    "birthday": "1981年01月31日",
    "age": "42歳",
    "height": "185cm",
    "weight": "81kg",
    "birthplace": "東京都",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "79",
    "real_name": "代田 建紀",
    "furigana": "だいた　たけのり",
    "birthday": "1974年02月11日",
    "age": "49歳",
    "height": "180cm",
    "weight": "77kg",
    "birthplace": "神奈川県",
    "bats_and_throws": "右投げ/両打ち"
  },
  {
    "uniform_number": "92",
    "real_name": "木田 優夫",
    "furigana": "きだ　まさお",
    "birthday": "1968年09月12日",
    "age": "54歳",
    "height": "187cm",
    "weight": "100kg",
    "birthplace": "東京都",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "84",
    "real_name": "伊藤 剛",
    "furigana": "いとう　たけし",
    "birthday": "1976年12月17日",
    "age": "46歳",
    "height": "185cm",
    "weight": "83kg",
    "birthplace": "神奈川県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "83",
    "real_name": "島崎 毅",
    "furigana": "しまざき　たけし",
    "birthday": "1967年03月03日",
    "age": "56歳",
    "height": "180cm",
    "weight": "80kg",
    "birthplace": "千葉県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "87",
    "real_name": "佐藤 友亮",
    "furigana": "さとう　ともあき",
    "birthday": "1978年06月13日",
    "age": "45歳",
    "height": "177cm",
    "weight": "88kg",
    "birthplace": "神奈川県",
    "bats_and_throws": "右投げ/右打ち"
  },
  {
    "uniform_number": "90",
    "real_name": "渡辺 浩司",
    "furigana": "わたなべ　ひろし",
    "birthday": "1963年08月09日",
    "age": "59歳",
    "height": "180cm",
    "weight": "76kg",
    "birthplace": "新潟県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "75",
    "real_name": "山中 潔",
    "furigana": "やまなか　きよし",
    "birthday": "1961年10月29日",
    "age": "61歳",
    "height": "178cm",
    "weight": "81kg",
    "birthplace": "大阪府",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "78",
    "real_name": "稲田 直人",
    "furigana": "いなだ　なおと",
    "birthday": "1979年11月06日",
    "age": "43歳",
    "height": "177cm",
    "weight": "80kg",
    "birthplace": "広島県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "76",
    "real_name": "紺田 敏正",
    "furigana": "こんた　としまさ",
    "birthday": "1980年08月12日",
    "age": "42歳",
    "height": "185cm",
    "weight": "80kg",
    "birthplace": "富山県",
    "bats_and_throws": "右投げ/左打ち"
  },
  {
    "uniform_number": "91",
    "real_name": "金子千尋",
    "furigana": "かねこ　ちひろ",
    "birthday": "1983年11月08日",
    "age": "39歳",
    "height": "180cm",
    "weight": "77kg",
    "birthplace": "新潟県",
    "bats_and_throws": "右投げ/左打ち"
  }
]
